name: Documentation

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.9
      - run: |
         python -m pip install --upgrade pip
         pip install -r requirements-dev.txt
         pip install -e .
      - run: mkdocs gh-deploy --force
